<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YgG_c7H' shared service.

return $this->privates['.service_locator.YgG_c7H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ProjectController::account' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController::delete_account' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController::delete_post' => ['privates', '.service_locator.NuQOKLc', 'get_ServiceLocator_NuQOKLcService.php', true],
    'App\\Controller\\ProjectController::newCat' => ['privates', '.service_locator.IKVNei_', 'get_ServiceLocator_IKVNeiService.php', true],
    'App\\Controller\\ProjectController::newPost' => ['privates', '.service_locator.n.YaE25', 'get_ServiceLocator_N_YaE25Service.php', true],
    'App\\Controller\\ProjectController::show' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController::showSearch' => ['privates', '.service_locator.6dQ.nU3', 'get_ServiceLocator_6dQ_NU3Service.php', true],
    'App\\Controller\\ProjectController::show_my_posts' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.ZONnbXs', 'get_ServiceLocator_ZONnbXsService.php', true],
    'App\\Controller\\ProjectController:account' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController:delete_account' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController:delete_post' => ['privates', '.service_locator.NuQOKLc', 'get_ServiceLocator_NuQOKLcService.php', true],
    'App\\Controller\\ProjectController:newCat' => ['privates', '.service_locator.IKVNei_', 'get_ServiceLocator_IKVNeiService.php', true],
    'App\\Controller\\ProjectController:newPost' => ['privates', '.service_locator.n.YaE25', 'get_ServiceLocator_N_YaE25Service.php', true],
    'App\\Controller\\ProjectController:show' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController:showSearch' => ['privates', '.service_locator.6dQ.nU3', 'get_ServiceLocator_6dQ_NU3Service.php', true],
    'App\\Controller\\ProjectController:show_my_posts' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.ZONnbXs', 'get_ServiceLocator_ZONnbXsService.php', true],
], [
    'App\\Controller\\ProjectController::account' => '?',
    'App\\Controller\\ProjectController::delete_account' => '?',
    'App\\Controller\\ProjectController::delete_post' => '?',
    'App\\Controller\\ProjectController::newCat' => '?',
    'App\\Controller\\ProjectController::newPost' => '?',
    'App\\Controller\\ProjectController::show' => '?',
    'App\\Controller\\ProjectController::showSearch' => '?',
    'App\\Controller\\ProjectController::show_my_posts' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\ProjectController:account' => '?',
    'App\\Controller\\ProjectController:delete_account' => '?',
    'App\\Controller\\ProjectController:delete_post' => '?',
    'App\\Controller\\ProjectController:newCat' => '?',
    'App\\Controller\\ProjectController:newPost' => '?',
    'App\\Controller\\ProjectController:show' => '?',
    'App\\Controller\\ProjectController:showSearch' => '?',
    'App\\Controller\\ProjectController:show_my_posts' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
