<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IKVNei_' shared service.

return $this->privates['.service_locator.IKVNei_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['privates', '.errored..service_locator.IKVNei_.Doctrine\\Common\\Persistence\\ObjectManager', NULL, 'Cannot autowire service ".service_locator.IKVNei_": it references interface "Doctrine\\Common\\Persistence\\ObjectManager" but no such service exists. Did you create a class that implements this interface?'],
], [
    'manager' => 'Doctrine\\Common\\Persistence\\ObjectManager',
]);
