<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZONnbXs' shared service.

return $this->privates['.service_locator.ZONnbXs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'manager' => ['privates', '.errored..service_locator.ZONnbXs.Doctrine\\Common\\Persistence\\ObjectManager', NULL, 'Cannot autowire service ".service_locator.ZONnbXs": it references interface "Doctrine\\Common\\Persistence\\ObjectManager" but no such service exists. Did you create a class that implements this interface?'],
], [
    'encoder' => '?',
    'manager' => 'Doctrine\\Common\\Persistence\\ObjectManager',
]);
