<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJbRMpUg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJbRMpUg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJbRMpUg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJbRMpUg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJbRMpUg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JbRMpUg',
    'container.build_id' => '3aac1939',
    'container.build_time' => 1578946990,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJbRMpUg');
