<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerICVplTI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerICVplTI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerICVplTI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerICVplTI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerICVplTI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ICVplTI',
    'container.build_id' => '893bc3f8',
    'container.build_time' => 1578003195,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerICVplTI');
