<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6dQ.nU3' shared service.

return $this->privates['.service_locator.6dQ.nU3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'annonceRepository' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService.php', true],
], [
    'annonceRepository' => 'App\\Repository\\AnnonceRepository',
]);
