<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBEbPv4T\srcApp_KernelAnnonceDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBEbPv4T/srcApp_KernelAnnonceDebugContainer.php') {
    touch(__DIR__.'/ContainerBEbPv4T.legacy');

    return;
}

if (!\class_exists(srcApp_KernelAnnonceDebugContainer::class, false)) {
    \class_alias(\ContainerBEbPv4T\srcApp_KernelAnnonceDebugContainer::class, srcApp_KernelAnnonceDebugContainer::class, false);
}

return new \ContainerBEbPv4T\srcApp_KernelAnnonceDebugContainer([
    'container.build_hash' => 'BEbPv4T',
    'container.build_id' => '5540438a',
    'container.build_time' => 1576114106,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBEbPv4T');
