<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wVKESr8' shared service.

return $this->privates['.service_locator.wVKESr8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ProjectController::account' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController::delete_account' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController::delete_post' => ['privates', '.service_locator.NuQOKLc', 'get_ServiceLocator_NuQOKLcService.php', true],
    'App\\Controller\\ProjectController::newCat' => ['privates', '.service_locator.z7Vzdpn', 'get_ServiceLocator_Z7VzdpnService.php', true],
    'App\\Controller\\ProjectController::newPost' => ['privates', '.service_locator.iD5Z6l5', 'get_ServiceLocator_ID5Z6l5Service.php', true],
    'App\\Controller\\ProjectController::search' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController::show' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController::showSearch' => ['privates', '.service_locator.6dQ.nU3', 'get_ServiceLocator_6dQ_NU3Service.php', true],
    'App\\Controller\\ProjectController::show_my_posts' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.FOsqNc4', 'get_ServiceLocator_FOsqNc4Service.php', true],
    'App\\Controller\\ProjectController:account' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController:delete_account' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController:delete_post' => ['privates', '.service_locator.NuQOKLc', 'get_ServiceLocator_NuQOKLcService.php', true],
    'App\\Controller\\ProjectController:newCat' => ['privates', '.service_locator.z7Vzdpn', 'get_ServiceLocator_Z7VzdpnService.php', true],
    'App\\Controller\\ProjectController:newPost' => ['privates', '.service_locator.iD5Z6l5', 'get_ServiceLocator_ID5Z6l5Service.php', true],
    'App\\Controller\\ProjectController:search' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController:show' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\ProjectController:showSearch' => ['privates', '.service_locator.6dQ.nU3', 'get_ServiceLocator_6dQ_NU3Service.php', true],
    'App\\Controller\\ProjectController:show_my_posts' => ['privates', '.service_locator.rEpYkl7', 'get_ServiceLocator_REpYkl7Service.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.FOsqNc4', 'get_ServiceLocator_FOsqNc4Service.php', true],
], [
    'App\\Controller\\ProjectController::account' => '?',
    'App\\Controller\\ProjectController::delete_account' => '?',
    'App\\Controller\\ProjectController::delete_post' => '?',
    'App\\Controller\\ProjectController::newCat' => '?',
    'App\\Controller\\ProjectController::newPost' => '?',
    'App\\Controller\\ProjectController::search' => '?',
    'App\\Controller\\ProjectController::show' => '?',
    'App\\Controller\\ProjectController::showSearch' => '?',
    'App\\Controller\\ProjectController::show_my_posts' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\ProjectController:account' => '?',
    'App\\Controller\\ProjectController:delete_account' => '?',
    'App\\Controller\\ProjectController:delete_post' => '?',
    'App\\Controller\\ProjectController:newCat' => '?',
    'App\\Controller\\ProjectController:newPost' => '?',
    'App\\Controller\\ProjectController:search' => '?',
    'App\\Controller\\ProjectController:show' => '?',
    'App\\Controller\\ProjectController:showSearch' => '?',
    'App\\Controller\\ProjectController:show_my_posts' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
