<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NuQOKLc' shared service.

return $this->privates['.service_locator.NuQOKLc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'annonce' => ['privates', '.errored..service_locator.NuQOKLc.App\\Entity\\Annonce', NULL, 'Cannot autowire service ".service_locator.NuQOKLc": it references class "App\\Entity\\Annonce" but no such service exists.'],
    'security' => ['privates', 'security.helper', 'getSecurity_HelperService.php', true],
], [
    'annonce' => 'App\\Entity\\Annonce',
    'security' => '?',
]);
